spring:
  application:
    name: IoTProject

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/iot  # 데이터베이스 URL
    username: root                          # 데이터베이스 사용자 이름
    password: keypass                              # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver          # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: update                                    # 스키마 자동 업데이트 (create, update, validate, none 중 선택)
    show-sql: false                                        # 실행된 SQL 출력 여부
    properties:
      hibernate:
        format_sql: true                                  # SQL 포맷팅
